### ISSUE TITLE
What is a chore?

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/DevelopmentConventions#11]
Our current definition of chore is rather weak since many of the other types are loosely defined:
1. Maintenance changes not covered by other types.

[Other possible definitons](https://www.reddit.com/r/github/comments/ghqqzr/why_do_people_put_chore_before_there_commits/fqbkzrb/) are:

2. Other changes that don't modify src or test files [[angular]](https://github.com/angular/angular/blob/511fe3d9f8c9eab0f97160a309b2df38804a43c0/CONTRIBUTING.md#Type)
3. Update something without impacting the user (ex: bump a dependency in package.json). [[source]](https://www.maxpou.fr/git-conventional-commits)
4. An Item that provides value to the Team or Product, as opposed to an external Stakeholder (e.g. improve the build script to incorporate module ABC) [[scrum]](https://scrumdictionary.com/term/chore/)
5. Changes to the build process or auxiliary tools and libraries such as documentation generation [[angular.js]](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type)
6. The regular or daily light work / A routine task or job [[dictionary]](https://www.merriam-webster.com/dictionary/chore)
6. Chore is a chore is a chore is a chore [[source]](https://en.wikipedia.org/wiki/Rose_is_a_rose_is_a_rose_is_a_rose)

Are we happy with our current wording?

**Comment by javier-godoy** [comment]
> some of those points can be of build or ci type (3 & 5 and 4 partially).

3 also overlaps with build/ci. I would only consider chore (under definitions 3 or 4) for the *other* changes. 

Note that 5 is actually deprecated:

> The prefix chore appears to have originated from Angular.js (1.x)’s Commit Message Guidelines, defined as:
>> Changes to the build process or auxiliary tools and libraries such as documentation generation.

> Angular 2’s convention introduces build (“Changes that affect the build system or external dependencies”) and ci (“Changes to our CI configuration files and scripts”). chore is redefined as “Other changes that don't modify src or test files”. 
The latest version of this convention removes the word chore entirely, with the commit that removes it stating:
>
Note that this PR removes support for "chore" which was previously overused by everyone on the team.

> So besides that I think that one additional use of chore would be to tag the changes to tooling configuration that doesn't apply to build or ci. Examples: maven-license-plugin, changes of IDE configurations if they're versioned, Docker Compose configuration maybe? ... etc.
Makes sense.

> Another example that I'm not completely sure is if we're modifying images (should we consider them to be part of the sources?)

It seems it could be a chore (under most definitions)

**Comment by javier-godoy** [comment]
So it seems the current definition is almost right,
> Maintenance changes not covered by other types.

Perhaps I would rewrite it as:
> Changes, not covered by other types, that don't modify source or test files.

What do you think?

**Comment by mlopezFC** [comment]
Totally agree with your proposal!
We can start with this definition and closely monitor the usage of this type and add further clarifications if we feel that they are needed.

**Comment by javier-godoy** [comment]
Modified:
>   - `chore:` Changes, not covered by other types
