### ISSUE TITLE
Proposal: WIP type

### ISSUE THREAD

**Issue by ngonzalezpazFC** [FlowingCode/DevelopmentConventions#16]
We came up with this situation in which I needed to push some changes in a branch, so another worker, @javier-godoy in this case, could continue with the issue. Those changes were incomplete, and did not solve the issue, so it seems wrong to use the "feat" type in an incomplete commit.
What do you think about having "WIP" type that can be combined with another type, like "revert" does. For example:

> wip: feat: add X functionality
> Description of the current status

I don't think these WIP commits should be in the master branch once finished, but could be useful for internal development.

**Comment by javier-godoy** [comment]
I like the idea. A branch can contain several commits, not all of them in progress (for instance, a completed refactoring and a feature implementation in progress). It also encourage committing work that isn't complete yet.
