### ISSUE TITLE
Type for fixing trivial code smells

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/DevelopmentConventions#18]
What is the recommended type for a commit that modifies the source code by doing a trivial commit, such as:
-  Replacing `result = result | visible;` with `result |= visible;`
-  Removing unused imports
-  Reordering modifiers (`final static` -> `static final`)
-  Adding curly braces.

Candidates are:
A.  `refactor:` Commits that **_contribute to the application source code_**. A code change that neither fixes a bug, nor adds a feature, nor implement a performance improvement.
B.  `style:` Trivial commits. Changes that **_do not affect the meaning of the code_** (white-space, formatting, missing semi-colons, etc).
C. `chore:` Changes, not covered by other types.

**Comment by javier-godoy** [comment]
**B.** If the changes are really trivial, the commit may have type `style`. None of the abovementioned examples is a `refactor`, because they preserve the logic, the structure and the behavior, i.e. *they do not affect the meaning of the code*. Commit of type `style` are not restricted to white-spaces and semicolons; the difference is semantic.

**Comment by mlopezFC** [comment]
Good catch. At this point I cannot think right now in an example of a refactor that changes the meaning of the code but it could be (for example a refactor might eliminate code that is not being executed or something like that).
In that case I agree that if the code change is trivial labeling as a _style_ change might be useful in order to "weight" the importance of the commit. So basically I agree with point **B**.

**Comment by ngonzalezpazFC** [comment]
I agree with you, the option B is a good choice for these kind of code smell fixes.

**Comment by mlopezFC** [comment]
Another thought that I have about this, is that maybe it's clear to know when something is a trivial change compared to a refactor. A refactor is usually something that is not _trivial_ (ie: package name change). In fact, a refactor can be a breaking change, but on the other hand a style change should never be a breaking change.
