### ISSUE TITLE
Define code style standards

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/DevelopmentConventions#19]
We should analyze if we could do something similar that we did with code conventions, but for code style standards.
That is basically taking a well known standard like [Google's](https://github.com/google/styleguide), and analyze the possibility of extending it (if we consider it necessary) and provide instructions for configuring the IDEs that we use in order to do the setup quickly and without problems.

**Comment by javier-godoy** [comment]
We have been using Google Code Style for a while, with no extensions. Let's call that 1.0.0.
