### ISSUE TITLE
Consider adding more examples

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/DevelopmentConventions#2]
Maybe it would be a good idea to add some "full" examples, specially regarding the body and the footer part.

**Comment by javier-godoy** [comment]
Examples: https://github.com/FlowingCode/DevelopmentConventions/issues/5#issuecomment-734936196

**Comment by ngonzalezpazFC** [comment]
If a commit has a "Co-authored-by" section, it should be on the footer section:



> test(demo): toggle production mode with checkbox
>
>Co-authored-by: Javier Godoy \<11554739+javier-godoy@users.noreply.github.com\>
>Fixes #6

The type of a commit that upgrades the addon version is "build"

>build: set version to 1.1.0-SNAPSHOT

**Comment by javier-godoy** [comment]
Document use of `revert`:

The SHA of the reverted commit must be indicated (either in the *body* or in the *footer*, so far we are not adding a requirement), and the commit *subject* must indicate the reverted *type*. 

```
revert: chore: update README.md

This reverts commit 7130274e055fb990ae03a164ebbcd367b1d3793a.
```

**Comment by javier-godoy** [comment]
@mlopezFC I added some examples in PR #15 
Please let me know if some other examples are needed (since the document is an **extension** of conventional commits, the reader can refer to that document for further examples)

**Comment by mlopezFC** [comment]
I think that the current examples are enough, I'm closing the ticket, thanks!
