### ISSUE TITLE
About removing and deprecating features

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/DevelopmentConventions#25]
Deprecating a feature correlates with MINOR in semver, and it's relevant for the release notes. 
 
`feat:` is defined as 
> `feat:` a new feature (correlates with MINOR in semantic versioning)

Since deprecating a feature is not "adding a new feature" some committers usually assign it type `chore:`, which implies either that it will not be included in release notes (fixes+features) or that all the chores have to be inspected when writing the release notes.

In the same line of thought, removing a existing feature, is neither a `feat:` nor a breaking `refactor:` ("_a code change that neither fixes a bug, nor adds a feature, nor implement a performance improvement_").

Proposal:

A) Allow `feat` to be used when deprecating or removing features
> `feat:` A new feature or deprecating an existing feature (correlates with MINOR in semantic versioning), or removing an existing feature (which is a breaking change).

--or--

B) Add a new type `unfeat:` that is specific for this case. 

> `unfeat:` Deprecating an existing feature (correlates with MINOR in semantic versioning) or removing it (which is a breaking change).

**Comment by mlopezFC** [comment]
I also like B, but what about using different name for removal and deprecations?:

> deprecate: Deprecating an existing feature (correlates with MINOR in semantic versioning)
> remove: Removing a feature (which is a breaking change)

My reasoning is that it easier to remember them. The problem is that they are too long words, but on the other hand they are probably not going to be used a lot, so maybe it is not going to be a huge issue.
