### ISSUE TITLE
Style Guide: Type inference for local variables

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/DevelopmentConventions#29]
The [Flowing Code Style Guide v1.0.0](https://github.com/FlowingCode/DevelopmentConventions/blob/ff8c709d939d7a497a81c64feea1d2e38bc44fd3/code-style.md)  doesn't specify where type inference for local variables (aka `var`) is acceptable. This language feature, which was added in Java 10, takes on special relevance as Java 8 LTS approaches end of life.

Some guidelines are mentioned in https://openjdk.java.net/projects/amber/guides/lvti-style-guide.

- [Choose variable names that provide useful information.](https://openjdk.java.net/projects/amber/guides/lvti-style-guide#G1)
- [Minimize the scope of local variables.](https://openjdk.java.net/projects/amber/guides/lvti-style-guide#G2)
- [Consider var when the initializer provides sufficient information to the reader.](https://openjdk.java.net/projects/amber/guides/lvti-style-guide#G3)
- [Use var to break up chained or nested expressions with local variables.](https://openjdk.java.net/projects/amber/guides/lvti-style-guide#G4)
- [Take care when using var with diamond or generic methods.](https://openjdk.java.net/projects/amber/guides/lvti-style-guide#G6)
- [Take care when using var with literals.](https://openjdk.java.net/projects/amber/guides/lvti-style-guide#G7)

**Comment by mlopezFC** [comment]
I think that if those guidelines are taken into account it's perfectly safe to use var. I would also comment two things:
1. It will be more likely in the future to find ourselves working with external projects using var, so we need to get used to that
2. The IDEs will help so it shouldn't be so drastic to find that in the code and don't know what to do for beginners.
So basically this LGTM
