### ISSUE TITLE
Style Guide: favor use of diamond constructor invocation

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/DevelopmentConventions#32]
The [Flowing Code Style Guide v1.0.0](https://github.com/FlowingCode/DevelopmentConventions/blob/ff8c709d939d7a497a81c64feea1d2e38bc44fd3/code-style.md) relies on Google Java Style Guide, which doesn't cover generics.

Particularly, it doesn't mention that diamond constructor invocation style is preferred.

I.e. 
```
Map<String,List<Integer>> map = new HashMap<>();
```
Instead of:
```
Map<String,List<Integer>> map = new HashMap<String,List<Integer>>();
```

**Comment by mlopezFC** [comment]
I prefer the first one, we should document it somewhere.
