### ISSUE TITLE
Differences between ci and build types -- round 2

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/DevelopmentConventions#35]
In #10 we discussed `build:` vs `ci:`. After a long discussion we settled in:

>build: Changes to the build process or external dependencies affecting the exported artifacts (i.e. those artifacts that are created as a result of such process, and are utilized as final deliverables or included in other external projects). Correlates with a PATCH, MINOR or MAJOR increment in semantic versioning, depending on the nature of the change
>
>ci: Changes to the CI configuration, and other changes to the build process or external dependencies with no impact in the exported artifacts (e.g.: configure code quality metrics, add dependencies that are only needed for running unit tests). Does not correlate with an increment in semantic versioning, because the versioned artifacts are not modified

In https://github.com/FlowingCode/CommonsDemo/pull/58#issuecomment-1671958232 it was argued that  `pom.xml` was actually _exported_ by the build process, making any change to that file potentially a commit of type `build:`

IMHO, the difference is that a commit of type `build:` introduces a _releasable_ change ("it correlates with a PATCH, MINOR or MAJOR increment in semantic versioning"), while a commit of type `ci:` doesn't ("does not correlate with an increment in semantic versioning, because the versioned artifacts are not modified")

I propose that we amend the conventions by stating a clarification in that sense.

**Comment by javier-godoy** [comment]
On 2023-09-18 we agreed on the proposal. The clarification text remains to be discussed.

**Comment by mlopezFC** [comment]
I was thinking about this a little bit more and I came to the conclusion that given that the pom.xml file is always included in the released artifact it will make ci type to almost disappear. There are some examples like modifications on github action scripts (it is ci because it will not affect the released artifact) and modification to pom files that are not released where ci can still be used. Maybe it is good because it will make things easier when deciding which type to use.

**Comment by flang** [comment]
I think that build: should apply to those commits that affects not only the final artifact, but also the end user of the component transitively. On the other side, even though a ci: commit could include pom.xml changes, end user shouldn't be affected by this kind of commit.
