### ISSUE TITLE
Javadoc style guide: deprecations

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/DevelopmentConventions#42]
There is a `@Deprecated` annotation, and there is also a `@deprecated` javadoc tag (that predates the annotation). 

There should be a guideline on which one to use.

```
  /** Sets the foo.
   * @param foo the foo to be set.
   * @deprecated Use {@code setFooBar} instead.*/
  @Deprecated(forRemoval = true)
  void setFoo(Object foo) {
    // ...
  }
```

**Comment by javier-godoy** [comment]
IMHO both must be required.
- The annotation provides an idiomatic way of indicating deprecations. It has runtime retention and optional since/forRemoval attributes.
- The javadoc tag allows an optional message providing additional information on the deprecation (e.g. whether the method was replaced, or whether a feature does not work as intended).

**Comment by paodb** [comment]
I agree that both should be present. [Here's some additional information](https://docs.oracle.com/en/java/javase/21/core/how-deprecate-apis.html) to the reasons Javier commented before.
